name: Build NestJS App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-nestjs:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: nest-todo-list

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build NestJS App
        run: npm run build
